### ISSUE TITLE
Error during download

### ISSUE THREAD

**Issue by arisliang** [zsdonghao/dcgan#11]
Tried twice, same error.

```
python download.py celebA
./data/img_align_celeba.zip: 25.5kB [12:15, 34.7B/s]Traceback (most recent call last):
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/urllib3/response.py", line 601, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/urllib3/response.py", line 557, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/http/client.py", line 614, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(5887 bytes read, 26881 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/requests/models.py", line 745, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/urllib3/response.py", line 432, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/urllib3/response.py", line 626, in read_chunked
    self._original_response.close()
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(5887 bytes read, 26881 more expected)', IncompleteRead(5887 bytes read, 26881 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download.py", line 164, in <module>
    download_celeb_a('./data')
  File "download.py", line 91, in download_celeb_a
    download_file_from_google_drive(drive_id, save_path)
  File "download.py", line 56, in download_file_from_google_drive
    save_response_content(response, destination)
  File "download.py", line 68, in save_response_content
    unit='B', unit_scale=True, desc=destination):
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/tqdm/_tqdm.py", line 962, in __iter__
    for obj in iterable:
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/requests/models.py", line 748, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(5887 bytes read, 26881 more expected)', IncompleteRead(5887 bytes read, 26881 more expected))
```

**Comment by zsdonghao** [comment]
hi, it run well on my side:

ubuntu 16
python2.7 and python3.5

```
haodong@haodong:/ssd2/Workspace/dcgan$ python download.py celebA
./data/img_align_celeba.zip: 44.1KB [00:18, 2.40KB/s]
haodong@haodong:/ssd2/Workspace/dcgan$ rm -rd data
haodong@haodong:/ssd2/Workspace/dcgan$ python3 download.py celebA
./data/img_align_celeba.zip: 44.1kB [00:13, 3.35kB/s]
```

**Comment by arisliang** [comment]
Tried again, it's ok now. Must be my network. Thanks.
