### ISSUE TITLE
ValueError: Trying to share variable discriminator/d/h4/lin_sigmoid/W

### ISSUE THREAD

**Issue by motkeg** [zsdonghao/dcgan#17]
hi,
I use:
 Tensorflow V 1.10 CPU version
Tensorlayer V 1.10.1
python 3.6
windows 10

after run : python main.py I get ValueError

Traceback (most recent call last):
  File "c:/Users/USER/Desktop/פרוייקט תואר שני/playgroung/dcgan/main.py", line 166, in <module>
    tf.app.run()
  File "C:\Python\3.6\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "c:/Users/USER/Desktop/פרוייקט תואר שני/playgroung/dcgan/main.py", line 59, in main
    _, d2_logits = discriminator(real_images, is_train=True, reuse=True)
  File "c:\Users\USER\Desktop\פרוייקט תואר שני\playgroung\dcgan\model.py", line 81, in discriminator
    W_init = w_init, name='d/h4/lin_sigmoid')
  File "c:\Users\USER\Desktop\פרוייקט תואר שני\playgroung\dcgan\tensorlayer\layers\core.py", line 926, in __init__
    W = tf.get_variable(name='W', shape=(n_in, n_units), initializer=W_init, dtype=LayersConfig.tf_dtype, **W_init_args)
  File "C:\Python\3.6\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1467, in get_variable
    aggregation=aggregation)
  File "C:\Python\3.6\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1217, in get_variable
    aggregation=aggregation)
  File "C:\Python\3.6\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 527, in get_variable
    aggregation=aggregation)
  File "C:\Python\3.6\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 481, in _true_getter
    aggregation=aggregation)
  File "C:\Python\3.6\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 853, in _get_single_variable
    found_var.get_shape()))
ValueError: Trying to share variable discriminator/d/h4/lin_sigmoid/W, but specified shape (8192, 1) and found shape (2048, 1).

**Comment by pskrunner14** [comment]
@motkeg it seems like a mismatch in input dimensions. Please see the changes in #16 and try running it again.

**Comment by motkeg** [comment]
Hi,
Thanks for replying - I solve the problem by doing 'git pull'.
probably I use the older version.
