### ISSUE TITLE
Error running train.py

### ISSUE THREAD

**Issue by ghost** [zsdonghao/dcgan#22]
Running train.py i get the following error:
```
Traceback (most recent call last):
  File "train.py", line 60, in <module>
    train()
  File "train.py", line 44, in train
    grad = tape.gradient(g_loss, G.trainable_weights)
AttributeError: 'Model' object has no attribute 'trainable_weights'
```
am i running a wrong version of tensorflow/tensorlayer (2.0.0a0/2.0.0)?

**Comment by zsdonghao** [comment]
hi, would you update the tensorlayer?
