### ISSUE TITLE
TypeError: __init__() got multiple values for keyword argument 'dtype'

### ISSUE THREAD

**Issue by carly666** [zsdonghao/dcgan#3]
### **When I try to run the repository to realize dcgan（After running python download.py mnist successfully, when running python main.py）, I meet the problem as follows.**

`Traceback (most recent call last):

  File "main.py", line 418, in <module>
    tf.app.run()
  File "/home/pcserver/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
 
_sys.exit(main(_sys.argv[:1] + flags_passthrough))

  File "main.py", line 290, in main
    net_g, g_logits = generator_simplified_api(z, is_train=True, reuse=False)

  File "main.py", line 104, in generator_simplified_api
    gamma_init=gamma_init, name='g/h0/batch_norm')

  File "/home/pcserver/car/dcgan-master/tensorlayer/layers.py", line 1732, in __init__
    initializer=beta_init)

  File "/home/pcserver/car/dcgan-master/tensorlayer/layers.py", line 1717, in _get_variable
    trainable=trainable)

  File "/home/pcserver/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)

  File "/home/pcserver/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)

  File "/home/pcserver/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)

  File "/home/pcserver/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)

  File "/home/pcserver/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 684, in _get_single_variable
    validate_shape=validate_shape)

  File "/home/pcserver/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 226, in __init__
    expected_shape=expected_shape)

  File "/home/pcserver/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 303, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)

  File "/home/pcserver/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 673, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)

TypeError: __init__() got multiple values for keyword argument 'dtype'`

## **The bold text "init" should be shown as "init" surrouded by two underline.**

**I cannot find any useful information on google to solve it, so I hope you will help me. @zsdonghao 
To make my question clear, my environment is tensorflow 1.0.1. Before that , I have replaced tf.nn.rnn_cell with tf.contrib.rnn to solve the question "No module object named rnn_cell".
And now, this new question makes me stopped.**

**Comment by zsdonghao** [comment]
please try again

**Comment by carly666** [comment]
oh，what could I say...
OK,I hope good news will arise in a few days.




Sent from Mail Master
On 04/11/2017 20:43, Hao wrote:

please try again
